<!--
Copyright © 2018 Wyomind. All rights reserved.
See LICENSE.txt for license details.
-->
<script>
    document.observe('dom:loaded', function () {
        if ($('datafeedmanager_category_filter').value == 1) {
            $('category_filter_0').checked = false;
            $('category_filter_1').checked = true;
        } else {
            $('category_filter_0').checked = true;
            $('category_filter_1').checked = false;
        }
        $$('.category_filter').each(function (r) {
            r.observe('click', function () {
                $('datafeedmanager_category_filter').value = r.value;
            });
        });
    });</script>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Filter the categories'); ?></h4>
    </div>
    <div class="fieldset" id="category-type">
        <div class="main-box">
            <input type="radio" value="0" name="category_filter" class="category_filter" id="category_filter_0" />
            <label for="category_filter_0"><?php echo $this->__("<b>Exclude</b> all products from the selected categories."); ?><br/></label>
            <input type="radio" value="1" name="category_filter" class="category_filter" id="category_filter_1" />
            <label for="category_filter_1"><?php echo $this->__("<b>Include</b> all products from the selected categories."); ?><br/></label>
        </div>
    </div>
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">
            <?php echo $this->__('Category selection and mapping'); ?>
        </h4>
    </div>
    <div class="fieldset category-selector" id="category-selector">
        <div id="taxonomy-box">
            Category mapping based on <select id="datafeed_taxonomy" name="datafeed_taxonomy">
                <?php
                $io = new Varien_Io_File();
                $array = $this->dirFiles($io->getCleanPath(Mage::getBaseDir() . "/lib/Wyomind"));

                foreach ($array as $key => $file) {
                    if (Mage::registry('datafeedmanager_data')->getDatafeedTaxonomy() == "/lib/Wyomind/" . $file) {
                        $selected = "selected";
                    } else {
                        $selected = "";
                    }
                    echo "<option value='" . "/lib/Wyomind/" . $file . "' $selected>" . basename($file) . "</option>";
                }
                ?> 
            </select>
        </div>
        <span id='note' style='margin-left:10px;'><?php echo $this->__("* If you do not select any category, all products will be exported"); ?></span>
        <textarea style="display:none" id="cat-json-tree"><?php echo $this->getJsonTree(); ?></textarea>
        <script>
            DFM_categories.autoCompleteUrl = "<?php echo $this->getUrl('*/*/categories'); ?>";
            // load selected categories
            DFM_categories.init();
            document.observe('click', function (evt) {
                var elt = evt.element();
                if (elt.hasClassName('tv-switcher')) {
                    if (elt.hasClassName('closed')) {
                        elt.removeClassName('closed');
                        elt.addClassName('opened');
                        DFM_categories.displayChildren(DFM_categories.tree[elt.id], "main-cat-" + elt.id);
                    } else if (elt.hasClassName('opened')) {
                        elt.addClassName('closed');
                        elt.removeClassName('opened');
                        $("main-cat-" + elt.id).up().select("ul").each(function (elt) {
                            elt.remove();
                        });
                    }
                } else if (elt.hasClassName("category")) {
                    elt.up().toggleClassName('selected');
                    DFM_categories.updateSelection();
                    DFM_categories.selectChildren(elt.id.replace("cat_id_", ""));
                } else if (elt.hasClassName("mapping")) {
                    DFM_categories.updateSelection();
                }
            });

            document.observe('keydown', function (evt) {
                var elt = evt.element();
                if (elt.hasClassName('mapping')) {
                    switch (evt.keyCode) {
                        case 35:
                            DFM_categories.updateChildrenMapping(elt.value, elt.id.replace('category_mapping_', ''));
                    }
                }
            });
        </script>
    </div>
</div>