<!--
Copyright © 2018 Wyomind. All rights reserved.
See LICENSE.txt for license details.
-->
<?php
$id = Mage::app()->getRequest()->getParam('id');
$data = Mage::getModel('datafeedmanager/configurations')->load($id);
$productTypes = Mage::getModel('catalog/product_type')->getOptionArray();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <div class="all_checkbox"><input class="check_all" type="checkbox" id="all_type_id" /></div>
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Product type'); ?></h4> 
    </div>
    <div class="fieldset" id="type-ids-selector">
        <div class="main-box">
            <?php foreach ($productTypes as $value => $label): ?>
                <div class="node">
                    <div class="cat-box">
                        <input type="checkbox" id="type_id_<?php echo $value; ?>" identifier="<?php echo $value; ?>"/>
                        <label for="type_id_<?php echo $value; ?>"><?php echo $label; ?></label>
                    </div>
                </div>
            <?php endforeach; ?>
            <input id="datafeedmanager_type_ids" name="datafeedmanager_type_ids" type="hidden"
                   class=" input-text required-entry" value="<?php echo $data->getDatafeedmanagerTypeIds(); ?>"
                   />
        </div>
    </div>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <div class="all_checkbox"><input class="check_all" type="checkbox" id="all_attribute_set" /></div>
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Attribute Set'); ?></h4>
    </div>
    <div class="fieldset" id="attribute-sets-selector">
        <div class="main-box">
            <?php
            $entityTypeId = Mage::getModel('eav/entity')->setType('catalog_product')->getTypeId();
            $attributeSet = Mage::getModel('eav/entity_attribute_set')->getCollection()->setEntityTypeFilter($entityTypeId);
            foreach ($attributeSet as $set): ?>
            <div class="node">
                <div class="cat-box">
                    <input type="checkbox" id="attribute_set_<?php echo $set->getId(); ?>" 
                           identifier="<?php echo $set->getId(); ?>" />
                    <?php echo $set->getAttributeSetName(); ?>
                </div>
            </div>
            <?php endforeach; ?>
            <input id="datafeedmanager_attribute_sets" name="datafeedmanager_attribute_sets" type="hidden"
                   value="<?php echo $data->getDatafeedmanagerAttributeSets(); ?>" class=" input-text required-entry" />
        </div>
    </div>
</div>
<div class='entry-edit'>
    <div class="entry-edit-head">
        <div class="all_checkbox"><input class="check_all" type="checkbox" id="all_visibility" /></div>
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Product visibility'); ?></h4>
    </div>
    <div class="fieldset" id="visibility-selector">
        <div class="main-box">
            <div class="node">
                <div class="cat-box">
                    <input type="checkbox" id="visibility_1" identifier="1"/>
                    <?php echo $this->__('Not Visible Individually'); ?>
                </div>
            </div>        
            <div class="node">
                <div class="cat-box">
                    <input type="checkbox" id="visibility_2" identifier="2"/>
                    <?php echo $this->__('Catalog'); ?>
                </div>
            </div>    
            <div class="node">
                <div class="cat-box">
                    <input type="checkbox" id="visibility_3" identifier="3"/>
                    <?php echo $this->__('Search'); ?>
                </div>
            </div>    
            <div class="node">
                <div class="cat-box">
                    <input type="checkbox" id="visibility_4" identifier="4"/>
                    <?php echo $this->__('Catalog, Search'); ?>
                </div>
            </div>    
            <input id="datafeedmanager_visibility" name="datafeedmanager_visibility" type="hidden"
                   value="<?php echo $data->getDatafeedmanagerVisibility(); ?>" class=" input-text required-entry" />
        </div>
    </div>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <div class="all_checkbox"><input class="check_all" type="checkbox" id="all_attribute" /></div>
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Advanced filters'); ?></h4>
    </div>
    <div class="fieldset" id="attributes-selector">
        <?php
        $attributesList = Mage::helper('datafeedmanager')->getOrderedAttributeList();
        $selectOutput = null;
        
        foreach ($attributesList as $attribute) {
            if (!empty($attribute['frontend_label'])) {
                $selectOutput.= "<option value='" . $attribute['attribute_code'] . "'>" 
                        . $attribute['frontend_label'] . "</option>";
            }
        }
        
        echo "<script>var _is_in_stock=[{\"label\":\"Yes\",\"value\":1},{\"label\":\"No\",\"value\":0}];"
            . "\nvar _qty=[];var _entity_id=[]; var _created_at=[]; var _updated_at=[];";
        foreach ($attributesList as $attribute) {
            if (preg_match("/^[a-zA-Z0-9_]+$/", $attribute['attribute_code'])) {
                if (isset($attribute['attribute_id']) && !stristr($attribute['attribute_code'], "ugiftcert")) {
                    $options = Mage::helper('datafeedmanager')->getAttributesOptions($attribute['attribute_id']);

                    if ($attribute['attribute_code'] != 'location') {
                        echo "\nvar _" . $attribute['attribute_code'] . "=" . json_encode($options) . ";";
                    }
                }
            }
        }
        echo "</script>";
        $filtersConfig = Mage::getStoreConfig('datafeedmanager/system/filters');
        for ($x = 0; $x <= $filtersConfig; $x++): ?>
            <div class="node" id="node_<?php echo $x; ?>">
                <?php 
                $size = '675px'; 
                if (Mage::getStoreConfig('datafeedmanager/system/filters_sql')): 
                    $size = '728px'; 
                endif; 
                ?>
                <div class="cat-box" style="width:<?php echo $size; ?>">
                    <input type="checkbox" id="attribute_<?php echo $x; ?>" identifier="<?php echo $x; ?>"/>
                    <?php 
                    if (!Mage::getStoreConfig('datafeedmanager/system/filters_sql')): 
                        $display = 'none'; 
                    else: 
                        $display = '';
                    endif;
                    if ($x > 0): ?>
                    <select style="width:50px; display:<?php echo $display; ?>" disabled="disabled" 
                            class="statement-attribute" id="statement_attribute_<?php echo $x; ?>" 
                            onchange='datafeedmanager.setValues($("attributes-selector"))' >
                        <option value="AND">AND</option>
                        <option value="OR">OR</option>
                    </select>
                    <?php else: ?>
                    <input type="text" id="statement_attribute_<?php echo $x; ?>" value="" class=" "
                           style="width:0;visibility:hidden;margin-right:48px; display:<?php echo $display; ?>" />
                    <?php endif; ?>
                    <select style="width:35px;display:none" disabled="disabled" class="parenthesis-open-attribute" 
                            id="parenthesis_open_attribute_<?php echo $x; ?>" 
                            onchange='datafeedmanager.setValues($("attributes-selector"))' >
                        <option value=""></option>
                        <option value="(">[</option>
                    </select>
                    <select style="width:300px" disabled="disabled" class="name-attribute" 
                            id="name_attribute_<?php echo $x; ?>" 
                            onchange='datafeedmanager.setValues($("attributes-selector"))' >
                        <?php echo $selectOutput; ?>
                    </select>
                    <select disabled="disabled" class="condition-attribute" id="condition_attribute_<?php echo $x; ?>" 
                            onchange='datafeedmanager.setValues($("attributes-selector"))' style="width:100px">
                        <option value="eq"><?php echo $this->__('=') ?></option>
                        <option value="gt"><?php echo $this->__('>') ?></option>
                        <option value="lt"><?php echo $this->__('<') ?></option>
                        <option value="gteq"><?php echo $this->__('&ge;') ?></option>
                        <option value="lteq"><?php echo $this->__('&le;') ?></option>
                        <option value="neq"><?php echo $this->__('&ne;') ?></option>
                        <option value="like"><?php echo $this->__('like') ?></option>
                        <option value="nlike"><?php echo $this->__('not like') ?></option>
                        <option value="null"><?php echo $this->__('is null') ?></option>
                        <option value="notnull"><?php echo $this->__('is not null') ?></option>
                        <option value="in"><?php echo $this->__('in') ?></option>
                        <option value="nin"><?php echo $this->__('not in') ?></option>
                    </select>
                    <select disabled="disabled" size="3" class="pre-value-attribute" multiple="multiple" 
                            id="pre-value-attribute_<?php echo $x; ?>" style="display:none;width:253px">
                    </select>
                    <?php $advanced = null;
                    if (Mage::getStoreConfig('datafeedmanager/system/filters_sql')): 
                        $advanced = 'advanced'; 
                    endif; ?>
                    <input disabled="disabled" type="text" id="value_attribute_<?php echo $x; ?>" style="width:250px"
                           class="value-attribute <?php echo $advanced; ?>" 
                           onkeyup='datafeedmanager.setValues($("attributes-selector"))'/>
                    <select style="width:35px; position: absolute; right: 9px; top: 0;display:none" 
                            disabled="disabled" class="parenthesis-close-attribute" 
                            id="parenthesis_close_attribute_<?php echo $x; ?>" 
                            onchange='datafeedmanager.setValues($("attributes-selector"))' >
                        <option value=""></option>
                        <option value=")">]</option>
                    </select>
                </div>
            </div>
        <?php endfor; ?>
    </div>
</div>