#! /bin/bash
rm ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form/Field/Extensions.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Edit/Tab/Configuration.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.10.0.1-7.10.0.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.11.0.1-7.11.0.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.11.0.2-7.11.0.3.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.11.0.3-7.11.0.4.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.12.0.1-7.12.0.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.12.0.3-7.12.0.4.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.12.0.4-7.12.0.5.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.12.0.5-7.12.0.6.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.12.0.6-7.12.0.7.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.12.0.7-7.12.0.8.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.13.0.1-7.13.0.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.12.0.2-7.12.0.3.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Edit/Tab/Categories.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.11.0-7.11.0.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.2.1-7.7.2.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.0.6-7.8.0.7.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.0.3-7.7.0.4.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.0.4-7.7.0.5.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.0.5-7.7.0.6.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.0.6-7.7.0.7.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.0.2-7.7.0.3.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.10.0.2-7.11.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.1.1-7.7.1.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.1.2-7.8.1.3.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.0.2-7.8.0.3.php
rm ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form/Field/Link.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.1.6-7.7.1.7.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.1.2-7.7.1.3.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.0.1-7.7.0.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.11.0.4-7.12.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.1.3-7.8.1.4.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.0.4-7.8.0.5.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.2.4-7.7.2.5.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.13.0.2-7.14.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.0.1-7.8.0.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.0.5-7.8.0.6.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.14.0-7.14.0.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.9.0.1-7.9.0.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.2.6-7.7.2.7.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.1.3-7.7.1.4.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.2.5-7.7.2.6.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.2.7.7-7.8.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.12.0-7.12.0.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.13.0-7.13.0.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.2.3-7.7.2.4.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.12.0.8-7.13.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.2.2-7.7.2.3.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.1.4-7.7.1.5.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.10.0-7.10.0.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.1.5-7.7.1.6.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.0.3-7.8.0.4.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.1.1-7.8.1.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.9.0.1-7.10.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.9.0.2-7.10.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.11.0-7.12.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.6.1-7.6.1.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.0-7.8.0.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Renderer/Process.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.1.7-7.7.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.13.0-7.14.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.2-7.7.2.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.12.0-7.13.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.9.0-7.9.0.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.6.1.1-7.7.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.10.0-7.11.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.1.4-7.9.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.1.1-7.9.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.0.7-7.8.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.0-7.7.0.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.0.7-7.7.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.1-7.7.1.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Edit/Tab/Filters.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.8.1-7.8.1.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.5.3b-6.6.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Renderer/Action.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Renderer/Status.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.5.2-6.5.3b.php
rm ./app/code/local/Wyomind/Datafeedmanager/controllers/Adminhtml/ConfigurationsController.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.4.1-3.4.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-5.0.0-5.0.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.4.1-6.5.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.4.0-7.4.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.4.1-7.4.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/controllers/Adminhtml/AttributesdfmController.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.3.2-7.4.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.3.1-7.3.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.3.0-7.3.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.2.0-7.3.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.4.2-7.4.3.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.5.2-3.6.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.6.0-6.6.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.4.4-7.5.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.7.3-3.7.4.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-5.0.1-5.0.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.3.0-3.4.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.1.0-3.2.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.2.0-3.3.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-2.6.1-3.0.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.0.0-3.1.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-2.5.1-2.5.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-2.5.2-2.6.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-2.3.1-2.4.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-2.4.1-2.5.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.6.1-7.7.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.6.0-7.6.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.5.1-7.6.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.4.0-3.4.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.7.4-3.7.5.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.5.3-6.6.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.0.1-6.1.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.2.0-6.2.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-5.2.0-5.3.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-5.3.1-6.0.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.4.2-3.4.3.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-5.0.2-5.1.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.6.0-3.7.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.5.1-6.5.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.5.1-3.5.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.6.1-7.0.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.5.0-3.5.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.4.4-3.5.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.4.3-3.4.4.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.3.0-6.4.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.7.0-3.7.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.7.0-7.8.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.7.1-3.7.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.1.0-7.1.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.7.2-3.7.3.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.1.1-7.2.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.4.3-7.4.4.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-5.1.0-5.2.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.0.0-7.1.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-5.3.0-5.3.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-7.5.0-7.5.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.0.0-6.0.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.7.6-4.0.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.1.0-6.2.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-4.0.0-4.1.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.2.1-6.3.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-4.1.0-4.1.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.4.0-6.4.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-4.1.1-4.1.2.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.5.0-6.5.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-4.1.2-5.0.0.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-6.5.2-6.5.3.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/upgrade-3.7.5-3.7.6.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Renderer/Link.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form/Field
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Edit/Tab/Cron.php
rm ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System/Config/Form/Field/Link.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Renderer/Type.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Edit/Tab/Ftp.php
rm ./app/code/local/Wyomind/Datafeedmanager/controllers/Adminhtml/OptionsdfmController.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Attributes/Renderer/Action.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Import/Edit/Tab/Uploader.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Attributes/Renderer/Code.php
rm ./app/code/local/Wyomind/Datafeedmanager/Model/Resource/Configurations/Collection.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Edit/Tabs.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Edit/Form.php
rm ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup/install-2.3.1.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Options/Renderer/Action.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Edit/Tab
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Renderer
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System/Config/Form/Field
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config/Form
rm ./app/code/local/Wyomind/Datafeedmanager/controllers/DatafeedmanagerController.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Options/Renderer/Code.php
rm ./app/code/local/Wyomind/Datafeedmanager/Model/Resource/Attributes/Collection.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Attributes/Edit/Form.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Edit
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Edit.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Attributes/Renderer
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations/Grid.php
rm ./app/design/adminhtml/default/default/template/datafeedmanager/categories.phtml
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Options/Edit/Form.php
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System/Config/Form
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System/Config
rm ./app/code/local/Wyomind/Datafeedmanager/Model/Resource/Options/Collection.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Import/Edit/Tabs.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Options/Renderer
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Import/Edit/Form.php
rm ./app/design/adminhtml/default/default/template/datafeedmanager/filters.phtml
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Attributes/Grid.php
rm ./app/code/local/Wyomind/Licensemanager/controllers/ActivationController.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Import/Edit/Tab
rm ./app/code/local/Wyomind/Datafeedmanager/Model/System/Config/Source/Urls.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Attributes/Edit.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Attributes/Edit
rm ./app/design/adminhtml/default/default/template/datafeedmanager/empty.phtml
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Configurations
rm ./app/code/local/Wyomind/Datafeedmanager/Model/Resource/Datafeedmanager.php
rm ./app/code/local/Wyomind/Datafeedmanager/Model/Resource/Configurations.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Model/Resource/Configurations
rm ./skin/adminhtml/default/default/CodeMirror2/mode/javascript/javascript.js
rm ./app/design/adminhtml/default/default/template/datafeedmanager/cron.phtml
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Options/Edit
rm ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/Notifications.php
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System/Config
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Options/Grid.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Options/Edit.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Import/Edit
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Model/System/Config/Source
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Attributes
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Categories.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Attributes.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml/System
rm ./app/code/local/Wyomind/Datafeedmanager/Model/Resource/Attributes.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Model/Resource/Attributes
rmdir  ./app/code/local/Wyomind/Datafeedmanager/sql/datafeedmanager_setup
rm ./app/code/local/Wyomind/Notificationmanager/Model/Resource/Setup.php
rm ./app/code/local/Wyomind/Datafeedmanager/Model/Product/Collection.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Options
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Library.php
rm ./skin/adminhtml/default/default/datafeedmanager/datafeedmanager.css
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Options.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Updater.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Import.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Import
rmdir  ./app/design/adminhtml/default/default/template/datafeedmanager
rm ./app/code/local/Wyomind/Datafeedmanager/Helper/Datafeedmanager.php
rm ./app/code/local/Wyomind/Datafeedmanager/Model/Resource/Options.php
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Sample.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Model/Resource/Options
rm ./skin/adminhtml/default/default/datafeedmanager/datafeedmanager.js
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Datafeedmanager.php
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml/System
rmdir  ./app/code/local/Wyomind/Datafeedmanager/controllers/Adminhtml
rm ./app/code/local/Wyomind/Datafeedmanager/Model/Configurations.php
rm ./app/code/local/Wyomind/Datafeedmanager/myRequiredAttributes.php
rm ./app/code/local/Wyomind/Licensemanager/Helper/Licensemanager.php
rm ./app/design/adminhtml/default/default/layout/datafeedmanager.xml
rm ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml/Ftp.php
rmdir  ./skin/adminhtml/default/default/CodeMirror2/mode/javascript
rm ./skin/adminhtml/default/default/datafeedmanager/AutoComplete.js
rm ./app/design/adminhtml/default/default/layout/licensemanager.xml
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Adminhtml
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Model/System/Config
rm ./skin/adminhtml/default/default/datafeedmanager/ajax-loader.gif
rm ./app/code/local/Wyomind/Datafeedmanager/myCustomAttributes.php
rm ./skin/adminhtml/default/default/datafeedmanager/treeview_m.png
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model/Resource
rm ./app/code/local/Wyomind/Notificationmanager/Model/Observer.php
rm ./skin/adminhtml/default/default/datafeedmanager/treeview_p.png
rm ./skin/adminhtml/default/default/CodeMirror2/lib/codemirror.css
rm ./skin/adminhtml/default/default/CodeMirror2/theme/default.css
rm ./skin/adminhtml/default/default/datafeedmanager/attributes.js
rm ./skin/adminhtml/default/default/CodeMirror2/lib/codemirror.js
rm ./app/code/local/Wyomind/Notificationmanager/etc/adminhtml.xml
rm ./app/code/local/Wyomind/Datafeedmanager/Helper/Categories.php
rm ./app/code/local/Wyomind/Datafeedmanager/Model/Attributes.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block/Adminhtml
rm ./skin/adminhtml/default/default/CodeMirror2/mode/css/css.js
rm ./skin/adminhtml/default/default/CodeMirror2/mode/php/php.js
rm ./skin/adminhtml/default/default/CodeMirror2/mode/xml/xml.js
rm ./app/code/local/Wyomind/Datafeedmanager/myCustomOptions.php
rm ./app/code/local/Wyomind/Notificationmanager/Helper/Data.php
rm ./app/code/local/Wyomind/Datafeedmanager/Model/Observer.php
rmdir  ./app/code/local/Wyomind/Licensemanager/Block/Adminhtml
rm ./skin/adminhtml/default/default/CodeMirror2/lib/runmode.js
rm ./skin/adminhtml/default/default/CodeMirror2/lib/overlay.js
rm ./app/code/local/Wyomind/Notificationmanager/etc/system.xml
rm ./app/code/local/Wyomind/Notificationmanager/etc/config.xml
rm ./app/code/local/Wyomind/Notificationmanager/Model/Feed.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Model/Resource
rm ./app/code/local/Wyomind/Licensemanager/Model/Observer.php
rm ./skin/adminhtml/default/default/datafeedmanager/arrow.png
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Model/Product
rm ./app/code/local/Wyomind/Datafeedmanager/Helper/Output.php
rm ./app/code/local/Wyomind/Datafeedmanager/Model/Options.php
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Model/System
rmdir  ./skin/adminhtml/default/default/CodeMirror2/mode/xml
rmdir  ./skin/adminhtml/default/default/CodeMirror2/mode/css
rmdir  ./skin/adminhtml/default/default/CodeMirror2/mode/php
rm ./app/code/local/Wyomind/Datafeedmanager/Model/Status.php
rm ./skin/adminhtml/default/default/datafeedmanager/index.js
rmdir  ./app/code/local/Wyomind/Datafeedmanager/controllers
rm ./app/code/local/Wyomind/Datafeedmanager/Helper/Data.php
rmdir  ./app/code/local/Wyomind/Licensemanager/controllers
rm ./app/code/local/Wyomind/Datafeedmanager/etc/system.xml
rm ./app/code/local/Wyomind/Licensemanager/Helper/Data.php
rmdir  ./app/code/local/Wyomind/Notificationmanager/Helper
rm ./app/code/local/Wyomind/Datafeedmanager/etc/config.xml
rm ./app/code/local/Wyomind/Licensemanager/etc/config.xml
rm ./skin/adminhtml/default/default/datafeedmanager/d.png
rmdir  ./skin/adminhtml/default/default/CodeMirror2/theme
rmdir  ./app/code/local/Wyomind/Notificationmanager/Model
rmdir  ./skin/adminhtml/default/default/CodeMirror2/mode
rmdir  ./app/code/local/Wyomind/Notificationmanager/etc
rmdir  ./skin/adminhtml/default/default/datafeedmanager
rm ./skin/adminhtml/default/default/CodeMirror2/LICENSE
rmdir  ./skin/adminhtml/default/default/CodeMirror2/lib
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Helper
rmdir  ./app/design/adminhtml/default/default/template
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Model
rmdir  ./app/code/local/Wyomind/Licensemanager/Helper
rmdir  ./app/code/local/Wyomind/Datafeedmanager/Block
rmdir  ./app/code/local/Wyomind/Licensemanager/Model
rmdir  ./app/code/local/Wyomind/Licensemanager/Block
rmdir  ./app/design/adminhtml/default/default/layout
rm ./app/etc/modules/Wyomind_Notificationmanager.xml
rmdir  ./skin/adminhtml/default/default/CodeMirror2
rmdir  ./app/code/local/Wyomind/Notificationmanager
rmdir  ./app/code/local/Wyomind/Datafeedmanager/sql
rmdir  ./app/code/local/Wyomind/Datafeedmanager/etc
rmdir  ./app/code/local/Wyomind/Licensemanager/etc
rm ./app/etc/modules/Wyomind_Datafeedmanager.xml
rmdir  ./app/code/local/Wyomind/Datafeedmanager
rm ./app/etc/modules/Wyomind_Licensemanager.xml
rmdir  ./app/code/local/Wyomind/Licensemanager
rmdir  ./app/design/adminhtml/default/default
rmdir  ./skin/adminhtml/default/default
rm ./shell/wyomind_datafeedmanager.php
rmdir  ./app/design/adminhtml/default
rm ./lib/Wyomind/Google_Taxonomy.txt
rmdir  ./app/code/local/Wyomind
rmdir  ./skin/adminhtml/default
rmdir  ./app/design/adminhtml
rm ./var/tmp/dfm/dfl_1.flag
rmdir  ./app/etc/modules
rmdir  ./skin/adminhtml
rmdir  ./app/code/local
rm ./feeds/sample.xml
rmdir  ./lib/Wyomind
rmdir  ./var/tmp/dfm
rmdir  ./app/design
rmdir  ./app/code
rm ./LICENSE.TXT
rmdir  ./app/etc
rmdir  ./var/tmp
rmdir  ./shell
rmdir  ./feeds
rmdir  ./skin
rmdir  ./var
rmdir  ./lib
rmdir  ./app